[package]
name = "castep_dos_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20.2"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.23"
winnow = "0.7.11"
